services:
  demo-app:
    image: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Share certificates with Nginx and Certbot containers
    ports:
      - "4201:80"
      - "443:443"
    networks:
      - demo-app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Persist certificates for sharing with Nginx
      - ./webroot:/var/www/certbot  # Required for webroot validation
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --agree-tos; sleep 12h; done;'"

  nginx:
    image: nginx:alpine
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Access updated certificates
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo-app
      - certbot
    ports:
      - "4201:80"
      - "443:443"

networks:
  demo-app-network:
    driver: bridge
