name: demo-app

services:
  main_app:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    image: tiagoeusebio/demo-app:latest
    labels:
      icon: https://icon.casaos.io/main/all/demo-app.png
    ports:
      - "80:80"    # Expose port for internal app access if needed
      - "443:443"  # Expose HTTPS
    restart: unless-stopped
    volumes:
       - ./letsencrypt:/etc/letsencrypt  # Mount for SSL certificates
       - ./webroot:/var/www/certbot      # Mount for Certbot validation
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Persist certificates for sharing with Nginx
      - ./webroot:/var/www/certbot       # Required for webroot validation
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --agree-tos; sleep 12h; done;'"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"   # HTTP, for redirecting to HTTPS
      - "443:443" # HTTPS
    volumes:
      - ./letsencrypt:/etc/letsencrypt      # Access SSL certificates
      - ./webroot:/var/www/certbot          # Serve Certbot validation files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx configuration
    depends_on:
      - main_app
      - certbot
    network_mode: bridge

x-casaos:
  author: self
  category: self
  hostname: tfae.ddns.net
  icon: https://icon.casaos.io/main/all/demo-app.png
  index: /
  is_uncontrolled: false
  port_map: "80"
  scheme: https
  store_app_id: demo-app
  title:
    custom: Demo App
